### ISSUE TITLE
Current state 2320e7e does not run (on Windows)

### ISSUE THREAD

**Issue by LimitlessGreen** [birdnet-team/BirdNET-Analyzer#86]
Hi, I'm trying to run the current main at 2320e7e0e193c484fde7f1727a87fad08b199932 under my Windows machine. 

<details>
  <summary>Installed Packages</summary>

  ```bash
# Name                    Version                   Build  Channel
absl-py                   1.4.0              pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
astor                     0.8.1              pyh9f0ad1d_0    conda-forge
audioread                 3.0.0            py37h03978a9_0    conda-forge
brotli                    1.0.9                hcfcfb64_8    conda-forge
brotli-bin                1.0.9                hcfcfb64_8    conda-forge
brotlipy                  0.7.0           py37hcc03f2d_1004    conda-forge
c-ares                    1.18.1               h8ffe710_0    conda-forge
ca-certificates           2022.12.7            h5b45459_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py37ha95fbe2_1    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
cryptography              38.0.2           py37h953a470_1    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
fonttools                 4.38.0           py37h51bd9d9_0    conda-forge
freetype                  2.12.1               h546665d_1    conda-forge
gast                      0.5.3              pyhd8ed1ab_0    conda-forge
google-pasta              0.2.0              pyh8c360ce_0    conda-forge
grpc-cpp                  1.48.1               h6a6baca_1    conda-forge
grpcio                    1.48.1           py37h2fbb7ef_1    conda-forge
h5py                      3.7.0           nompi_py37h24adfc3_101    conda-forge
hdf5                      1.12.2          nompi_h57737ce_101    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.4           py37h03978a9_0    conda-forge
intel-openmp              2023.0.0         h57928b3_25922    conda-forge
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   hcfcfb64_3    conda-forge
keras-applications        1.0.8                      py_1    conda-forge
keras-preprocessing       1.1.2              pyhd8ed1ab_0    conda-forge
kiwisolver                1.4.4            py37h8c56517_0    conda-forge
krb5                      1.20.1               heb0366b_0    conda-forge
lame                      3.100             hcfcfb64_1003    conda-forge
lazy_loader               0.1                pyhd8ed1ab_1    conda-forge
lcms2                     2.14                 h90d422f_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libabseil                 20220623.0      cxx17_h1a56200_6    conda-forge
libaec                    1.0.6                h63175ca_1    conda-forge
libblas                   3.9.0              16_win64_mkl    conda-forge
libbrotlicommon           1.0.9                hcfcfb64_8    conda-forge
libbrotlidec              1.0.9                hcfcfb64_8    conda-forge
libbrotlienc              1.0.9                hcfcfb64_8    conda-forge
libcblas                  3.9.0              16_win64_mkl    conda-forge
libcurl                   7.88.1               h68f0423_1    conda-forge
libdeflate                1.14                 hcfcfb64_0    conda-forge
libflac                   1.4.2                h63175ca_0    conda-forge
libhwloc                  2.9.0                h51c2c0f_0    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
liblapack                 3.9.0              16_win64_mkl    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libopus                   1.3.1                h8ffe710_1    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libprotobuf               3.21.8               h12be248_0    conda-forge
librosa                   0.10.0             pyhd8ed1ab_2    conda-forge
libsndfile                1.2.0                h2628c91_0    conda-forge
libsqlite                 3.40.0               hcfcfb64_0    conda-forge
libssh2                   1.10.0               h9a1e1f7_3    conda-forge
libtiff                   4.4.0                hc4f729c_5    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp-base              1.3.0                hcfcfb64_0    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libxml2                   2.10.3               hc3477c8_6    conda-forge
libzlib                   1.2.13               hcfcfb64_4    conda-forge
llvmlite                  0.39.1           py37h0c9d48c_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markdown                  3.4.2              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.1            py37hcc03f2d_1    conda-forge
matplotlib-base           3.5.3            py37hbaab90a_2    conda-forge
mkl                       2022.1.0           h6a75c08_874    conda-forge
mpg123                    1.31.3               h63175ca_0    conda-forge
msgpack-python            1.0.4            py37h8c56517_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
numba                     0.56.3           py37h9c05cb2_0    conda-forge
numpy                     1.21.6           py37h2830a78_0    conda-forge
openjpeg                  2.5.0                hc9384bd_1    conda-forge
openssl                   3.1.0                hcfcfb64_0    conda-forge
packaging                 23.0               pyhd8ed1ab_0    conda-forge
pillow                    9.2.0            py37h42a8222_2    conda-forge
pip                       23.0.1             pyhd8ed1ab_0    conda-forge
pooch                     1.6.0              pyhd8ed1ab_0    conda-forge
protobuf                  4.21.8           py37h7f67f24_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 23.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py37h03978a9_5    conda-forge
pysoundfile               0.12.1             pyhd8ed1ab_0    conda-forge
python                    3.7.12          h900ac77_100_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.7                     3_cp37m    conda-forge
re2                       2022.06.01           h0e60522_1    conda-forge
requests                  2.28.2             pyhd8ed1ab_0    conda-forge
scikit-learn              1.0.2            py37hcabfae0_0    conda-forge
scipy                     1.7.3            py37hb6553fb_0    conda-forge
setuptools                67.6.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
soxr                      0.1.3                hcfcfb64_3    conda-forge
soxr-python               0.3.2            py37h0b711f8_0    conda-forge
sqlite                    3.40.0               hcfcfb64_0    conda-forge
tbb                       2021.8.0             h91493d7_0    conda-forge
tensorboard               1.14.0                   py37_0    conda-forge
tensorflow                1.14.0               h1f41ff6_0    conda-forge
tensorflow-base           1.14.0           py37hc8dfbb8_0    conda-forge
tensorflow-estimator      1.14.0           py37h5ca1d4c_0    conda-forge
termcolor                 2.2.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
typing-extensions         4.5.0                hd8ed1ab_0    conda-forge
typing_extensions         4.5.0              pyha770c72_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
unicodedata2              14.0.0           py37hcc03f2d_1    conda-forge
urllib3                   1.26.15            pyhd8ed1ab_0    conda-forge
vc                        14.3                hb6edc58_10    conda-forge
vs2015_runtime            14.34.31931         h4c5c07a_10    conda-forge
werkzeug                  2.2.3              pyhd8ed1ab_0    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
wrapt                     1.14.1           py37hcc03f2d_0    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hcfcfb64_4    conda-forge
zstd                      1.5.2                h12be248_6    conda-forge

 ```

</details>

I tried to run a simple `python .\analyze.py`, but getting this error: 
```bash
> python .\analyze.py
Species list contains 3337 species
Found 1 files to analyze
Analyzing example/\soundscape.wav
Traceback (most recent call last):
  File "D:\workspace\BirdNET-Analyzer\analyze.py", line 268, in analyzeFile
    p = predict(samples)
  File "D:\workspace\BirdNET-Analyzer\analyze.py", line 217, in predict
    prediction = model.predict(data)
  File "D:\workspace\BirdNET-Analyzer\model.py", line 121, in predict
    loadModel()
  File "D:\workspace\BirdNET-Analyzer\model.py", line 38, in loadModel
    INTERPRETER = tflite.Interpreter(model_path=cfg.MODEL_PATH, num_threads=cfg.TFLITE_THREADS)
TypeError: __init__() got an unexpected keyword argument 'num_threads'

Error: Cannot analyze audio file example/\soundscape.wav.
Traceback (most recent call last):
  File "D:\workspace\BirdNET-Analyzer\analyze.py", line 268, in analyzeFile
    p = predict(samples)
  File "D:\workspace\BirdNET-Analyzer\analyze.py", line 217, in predict
    prediction = model.predict(data)
  File "D:\workspace\BirdNET-Analyzer\model.py", line 121, in predict
    loadModel()
  File "D:\workspace\BirdNET-Analyzer\model.py", line 38, in loadModel
    INTERPRETER = tflite.Interpreter(model_path=cfg.MODEL_PATH, num_threads=cfg.TFLITE_THREADS)
TypeError: __init__() got an unexpected keyword argument 'num_threads
```

The packed Windows zip does run btw.

**Comment by LimitlessGreen** [comment]
It may be related to the fact that TensorFlow is no longer supported by Windows native.
https://www.tensorflow.org/install/pip#windows-native
![grafik](https://user-images.githubusercontent.com/15064073/228240911-a47aa3bb-17fa-4603-b0e8-ca34f0b6b1db.png)

**Comment by LimitlessGreen** [comment]
Can confirm, it's running under Windows on wsl2.
